alertmanager:
  enabled: false
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeEtcd:
  enabled: false
kubeProxy:
  enabled: false
defaultRules:
  rules:
    kubeControllerManager: false
    kubeSchedulerAlerting: false
    kubeSchedulerRecording: false
    etcd: false
    kubeProxy: false
grafana:
  service:
    type: ClusterIP
  admin:
    existingSecret: grafana-admin
    userKey: admin-user
    passwordKey: admin-password
  persistence:
    enabled: false
prometheus:
  service:
    type: ClusterIP
  prometheusSpec:
    replicas: 1
    retention: 24h
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        memory: 2Gi
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: managed-csi
          accessModes: [ReadWriteOnce]
          resources:
            requests:
              storage: 10Gi
